version: '3'

services:
  mysql:
    image: mysql:5.7.31
    container_name: mysql-5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      - default
      
  postgres:
    image: postgres:9.6
    container_name: postgres-9.6
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    networks:
      - default
      
  mongo:
    image: mongo:3.6.19
    container_name: mongo-3.6
    ports:
      - '27017:27017'
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks: 
      - default
      
  # http://localhost:5984/_utils/# 
  couchdb:
    image: couchdb:3.1
    container_name: couchdb-3.1
    ports:
      - '5984:5984'
    restart: unless-stopped
    volumes:
      - ./couchdb_data:/opt/couchdb/etc/local.d -d couchdb
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: secret
    networks:
      - default

  redis:
    image: redis:3.0
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - default

  # http://localhost:8080
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks: 
      - default
  
  # http://localhost:9000
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - '8181:8000'
      - '9000:9000'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - default

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    networks:
      - default

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  couchdb_data:
    driver: local
  portainer_data:
    driver: local

networks:
  default:
    external:
      name: db_network
